services:
    db:
        container_name: postgres-spring-boot
        image: postgres:latest
        environment:
            POSTGRES_USER: memento
            POSTGRES_PASSWORD: password
            #where data is stored
            PGDATA: /data/postgres
        volumes:
            - db:/data/postgres
        ports:
            - "5332:5432"
        networks:
            - db
        restart: unless-stopped

#if you have more than 1 container and you want them to talk with each other
networks:
    db:
        driver: bridge
volumes:
    db: